# Generated by Django 5.2.5 on 2025-08-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='contact', verbose_name='Imagen del producto')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('product', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('category', models.CharField(choices=[('PAN', 'Panadería'), ('BEB', 'Bebidas'), ('LIM', 'Limpieza'), ('OTR', 'Otros')], max_length=50, verbose_name='Categoría')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio de venta')),
                ('stock', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Stock disponible')),
                ('supplier', models.CharField(blank=True, max_length=50, null=True, verbose_name='Proveedor')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
        ),
    ]
